
dist: focal

language: go
go:
- 1.16.x
- 1.15.x
addons:
  apt:
    packages:
    - rpm
go_import_path: github.com/nats-io/nats-server
install:
- make install-tools
before_script:
- make lint
script:
- set -e
- if [[ $TRAVIS_TAG ]]; then make test-tag; fi
- if [[ ! $TRAVIS_TAG ]]; then make test-no-race; fi
- if [[ ! $TRAVIS_TAG ]]; then if [[ "$TRAVIS_GO_VERSION" =~ 1.15 ]]; then ./scripts/cov.sh TRAVIS; else make test; fi; fi
- set +e

deploy:
  provider: script
  cleanup: true
  script: curl -sL http://git.io/goreleaser | VERSION=v0.160.0 bash
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ 1.16
