name: NATS Server Testing
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.16]

    env:
      GOPATH: /home/runner/work/nats-server

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: src/github.com/nats-io/nats-server

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Install tools
        run: make install-tools

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test-no-race test
